### ISSUE TITLE
MA03: Os botões de Ações no responsivo(de todos os CRUDs) está ocupando duas linhas na grid, deveria ocupar apenas uma.

### ISSUE THREAD

**Issue by GeovRodri** [GeovRodri/GestaoPetShop-POO2#8]
- Nível de dificuldade: fácil.
- Tempo estimado: 2 horas
	Essa tarefa é referente ao responsivo, ou seja, a visualização por diversos dispositivos diferentes. No celular (testado no Moto G5S) as telas de listagens está com uma pequena falha no design, os botões da última coluna está quebrando linha e não deveria.

**Comment by jpdesiderio** [comment]
Foi mais fácil que a maldita checkbox.
