### ISSUE TITLE
MA04: Melhoria na interface do cadastro de Clientes, existe um espaço que pode ser preenchido com um campo sem a necessidade de pular de linha.

### ISSUE THREAD

**Issue by GeovRodri** [GeovRodri/GestaoPetShop-POO2#9]
- Nível de dificuldade: fácil.
- Tempo estimado: 2 horas
	O campo de telefone deve subir para primeira linha para ocupar o espaço em branco e o endereço deve ocupar a linha toda.

**Comment by jpdesiderio** [comment]
Foi fácil.
